version: '3.8'

services:
  db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./express-api/seed-data:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  express-api:
    build:
      context: ./express-api
    env_file:
      - ./express-api/.env
    restart: always
    depends_on:
      - db
    networks:
      - backend
      - frontend

  nuxt-client:
    build:
      context: ./nuxt-app
    env_file:
      - ./nuxt-app/.env
    ports:
      - "3002:3000"
    restart: always
    depends_on:
      - express-api
    networks:
      - frontend

volumes:
  db_data:

networks:
  frontend:
  backend: