version: '3.8'

services:
  nuxt:
    build: .
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - express

  express:
    build:
      context: ../express-mysql-api
    ports:
      - "3000:3000"
    env_file:
      - ../express-mysql-api/.env

  db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sampledb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
